"""Performance tracking database for the learning loop.

Schema:
- videos: one row per uploaded video with features + metrics
- snapshots: periodic metric snapshots to track growth over time
- experiments: A/B test records (varied parameter + outcome)
- insights: natural-language learnings generated by LLM
- recommendations: next-action suggestions for upcoming videos
"""
from __future__ import annotations

import json
import logging
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Optional

log = logging.getLogger(__name__)


SCHEMA = """
CREATE TABLE IF NOT EXISTS videos (
    video_id TEXT PRIMARY KEY,
    channel_id TEXT,
    title TEXT,
    published_at TEXT,
    features_json TEXT,
    first_seen_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    video_id TEXT NOT NULL,
    snapshot_at TEXT NOT NULL,
    days_old REAL,
    view_count INTEGER,
    like_count INTEGER,
    comment_count INTEGER,
    engagement_rate REAL,
    FOREIGN KEY (video_id) REFERENCES videos(video_id)
);

CREATE TABLE IF NOT EXISTS experiments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    video_id TEXT,
    variable TEXT,
    value TEXT,
    baseline_value TEXT,
    result_metric TEXT,
    result_value REAL,
    baseline_value_metric REAL,
    delta_percent REAL,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS insights (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    generated_at TEXT NOT NULL,
    channel_id TEXT,
    category TEXT,
    insight TEXT,
    confidence REAL,
    supporting_video_ids TEXT,
    applied BOOLEAN DEFAULT 0
);

CREATE TABLE IF NOT EXISTS recommendations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT NOT NULL,
    channel_id TEXT,
    category TEXT,
    recommendation TEXT,
    rationale TEXT,
    priority INTEGER DEFAULT 3,
    status TEXT DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS sentiments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    video_id TEXT,
    fetched_at TEXT,
    total_comments INTEGER,
    positive_count INTEGER,
    neutral_count INTEGER,
    negative_count INTEGER,
    top_themes TEXT,
    sample_positive TEXT,
    sample_negative TEXT
);

CREATE INDEX IF NOT EXISTS idx_snapshots_video ON snapshots(video_id);
CREATE INDEX IF NOT EXISTS idx_insights_generated ON insights(generated_at);
CREATE INDEX IF NOT EXISTS idx_recommendations_status ON recommendations(status);
"""


class LearningDB:
    def __init__(self, db_path: str = "learning.db"):
        self.db_path = Path(db_path)
        self.conn = sqlite3.connect(str(self.db_path), check_same_thread=False)
        self.conn.row_factory = sqlite3.Row
        self.conn.executescript(SCHEMA)
        self.conn.commit()
        log.info("Learning DB ready at %s", self.db_path)

    # ── Videos ────────────────────────────────────────────────────

    def upsert_video(self, video_id: str, channel_id: str, title: str,
                     published_at: str, features: dict):
        self.conn.execute(
            """INSERT OR REPLACE INTO videos
               (video_id, channel_id, title, published_at, features_json, first_seen_at)
               VALUES (?, ?, ?, ?, ?,
                       COALESCE((SELECT first_seen_at FROM videos WHERE video_id = ?), ?))""",
            (video_id, channel_id, title, published_at,
             json.dumps(features, default=str),
             video_id, datetime.utcnow().isoformat()),
        )
        self.conn.commit()

    def get_all_videos(self) -> list[dict]:
        rows = self.conn.execute("SELECT * FROM videos").fetchall()
        return [dict(r) for r in rows]

    # ── Snapshots ─────────────────────────────────────────────────

    def record_snapshot(self, video_id: str, metrics: dict):
        views = metrics.get("view_count", 0)
        likes = metrics.get("like_count", 0)
        comments = metrics.get("comment_count", 0)
        engagement = (likes + comments * 2) / views if views > 0 else 0

        # Days old since first_seen
        row = self.conn.execute(
            "SELECT first_seen_at FROM videos WHERE video_id = ?", (video_id,)
        ).fetchone()
        days_old = 0
        if row:
            try:
                first = datetime.fromisoformat(row["first_seen_at"])
                days_old = (datetime.utcnow() - first).total_seconds() / 86400
            except Exception:
                pass

        self.conn.execute(
            """INSERT INTO snapshots
               (video_id, snapshot_at, days_old, view_count, like_count, comment_count, engagement_rate)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            (video_id, datetime.utcnow().isoformat(), days_old,
             views, likes, comments, engagement),
        )
        self.conn.commit()

    def latest_snapshot(self, video_id: str) -> Optional[dict]:
        row = self.conn.execute(
            "SELECT * FROM snapshots WHERE video_id = ? ORDER BY snapshot_at DESC LIMIT 1",
            (video_id,),
        ).fetchone()
        return dict(row) if row else None

    def get_growth_history(self, video_id: str) -> list[dict]:
        rows = self.conn.execute(
            "SELECT * FROM snapshots WHERE video_id = ? ORDER BY snapshot_at",
            (video_id,),
        ).fetchall()
        return [dict(r) for r in rows]

    # ── Insights ──────────────────────────────────────────────────

    def save_insight(self, channel_id: str, category: str, insight: str,
                     confidence: float, supporting_ids: list[str]):
        self.conn.execute(
            """INSERT INTO insights
               (generated_at, channel_id, category, insight, confidence, supporting_video_ids)
               VALUES (?, ?, ?, ?, ?, ?)""",
            (datetime.utcnow().isoformat(), channel_id, category, insight,
             confidence, json.dumps(supporting_ids)),
        )
        self.conn.commit()

    def get_insights(self, channel_id: str = None, limit: int = 50) -> list[dict]:
        q = "SELECT * FROM insights"
        p = ()
        if channel_id:
            q += " WHERE channel_id = ?"
            p = (channel_id,)
        q += " ORDER BY generated_at DESC LIMIT ?"
        rows = self.conn.execute(q, p + (limit,)).fetchall()
        return [dict(r) for r in rows]

    # ── Recommendations ───────────────────────────────────────────

    def save_recommendation(self, channel_id: str, category: str,
                           recommendation: str, rationale: str, priority: int = 3):
        self.conn.execute(
            """INSERT INTO recommendations
               (created_at, channel_id, category, recommendation, rationale, priority)
               VALUES (?, ?, ?, ?, ?, ?)""",
            (datetime.utcnow().isoformat(), channel_id, category,
             recommendation, rationale, priority),
        )
        self.conn.commit()

    def get_pending_recommendations(self, channel_id: str = None) -> list[dict]:
        q = "SELECT * FROM recommendations WHERE status = 'pending'"
        p = ()
        if channel_id:
            q += " AND channel_id = ?"
            p = (channel_id,)
        q += " ORDER BY priority DESC, created_at DESC"
        rows = self.conn.execute(q, p).fetchall()
        return [dict(r) for r in rows]

    def mark_applied(self, rec_id: int):
        self.conn.execute(
            "UPDATE recommendations SET status = 'applied' WHERE id = ?", (rec_id,)
        )
        self.conn.commit()

    # ── Sentiments ────────────────────────────────────────────────

    def save_sentiment(self, video_id: str, sentiment_data: dict):
        self.conn.execute(
            """INSERT INTO sentiments
               (video_id, fetched_at, total_comments, positive_count, neutral_count,
                negative_count, top_themes, sample_positive, sample_negative)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (video_id, datetime.utcnow().isoformat(),
             sentiment_data.get("total", 0),
             sentiment_data.get("positive", 0),
             sentiment_data.get("neutral", 0),
             sentiment_data.get("negative", 0),
             json.dumps(sentiment_data.get("themes", [])),
             json.dumps(sentiment_data.get("sample_positive", [])),
             json.dumps(sentiment_data.get("sample_negative", []))),
        )
        self.conn.commit()

    # ── Analysis helpers ──────────────────────────────────────────

    def get_top_performers(self, channel_id: str = None, limit: int = 10) -> list[dict]:
        """Get top-performing videos by latest view count."""
        q = """
            SELECT v.video_id, v.title, v.published_at, v.features_json,
                   s.view_count, s.like_count, s.comment_count, s.engagement_rate
            FROM videos v
            LEFT JOIN (
                SELECT video_id, MAX(snapshot_at) as max_at
                FROM snapshots GROUP BY video_id
            ) latest ON v.video_id = latest.video_id
            LEFT JOIN snapshots s ON s.video_id = v.video_id AND s.snapshot_at = latest.max_at
        """
        p = ()
        if channel_id:
            q += " WHERE v.channel_id = ?"
            p = (channel_id,)
        q += " ORDER BY s.view_count DESC LIMIT ?"
        rows = self.conn.execute(q, p + (limit,)).fetchall()
        return [dict(r) for r in rows]

    def get_all_with_metrics(self, channel_id: str = None) -> list[dict]:
        q = """
            SELECT v.video_id, v.title, v.published_at, v.features_json,
                   s.view_count, s.like_count, s.comment_count, s.engagement_rate, s.days_old
            FROM videos v
            LEFT JOIN (
                SELECT video_id, MAX(snapshot_at) as max_at
                FROM snapshots GROUP BY video_id
            ) latest ON v.video_id = latest.video_id
            LEFT JOIN snapshots s ON s.video_id = v.video_id AND s.snapshot_at = latest.max_at
        """
        p = ()
        if channel_id:
            q += " WHERE v.channel_id = ?"
            p = (channel_id,)
        rows = self.conn.execute(q, p).fetchall()
        return [dict(r) for r in rows]

    def close(self):
        self.conn.close()
